/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import "./../../bearcss.config.js";
import { Dosis, Inter } from "next/font/google";
import Image from "next/image.js";
const dosis = Dosis({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/beercss@3.4.2/dist/cdn/beer.min.css"
          rel="stylesheet"
        />
        <script
          type="module"
          src="https://cdn.jsdelivr.net/npm/beercss@3.4.2/dist/cdn/beer.min.js"
        ></script>
        <script
          type="module"
          src="https://cdn.jsdelivr.net/npm/material-dynamic-colors@1.1.0/dist/cdn/material-dynamic-colors.min.js"
        ></script>
      </head>
      <body
        className={`font-sans ${dosis.className} ${inter.className} grey10 center-align`}
      >
        <header className="transparent">
          <Image
            className=""
            src="/images/logo.svg"
            alt="logo"
            width={200}
            height={200}
          />
        </header>

        {children}
      </body>
    </html>
  );
}
